CREATE USER BOM_CATALOGO IDENTIFIED BY "123456" QUOTA UNLIMITED ON USERS;
CREATE USER BOMERP_APP IDENTIFIED BY "123456";
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO BOM_CATALOGO;
GRANT CREATE SESSION TO BOMERP_APP;
EXIT;
